language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
